version: '3.7'
services:
  serenify-database:
    image: postgres:latest
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: serenify-db
    volumes:
      - serenify-data:/var/lib/postgresql/data
    networks:
      - serenify-network

  serenify:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - serenify-network
    depends_on:
      - serenify-database
    command: sh -c "while ! nc -z serenify-database 5432; do sleep 1; done && npx prisma db push && npm run start"

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - serenify
    networks:
      - serenify-network

networks:
  serenify-network:

volumes:
  serenify-data:
