version: '3.8'
services:
  todo-db:
    image: postgres:15
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: serenify-db
    networks:
      - serenify-pg

  serenify:
  container_name: serenify
  build: .
  ports:
    - 3000
  restart: always

  proxy:
    build: nginx/
    ports:
      - '80:80'
    depends_on:
      - serenify
    restart: always

networks:
  serenify-pg:
